#!/usr/bin/env python3
"""Write the line -> archive entry mapping the app ships with.

The national JDF archive names its entries with opaque ids, so a line cannot be
asked for by number. This scans the archive once, offline, and writes the mapping
for the lines that touch the region. The app fetches the archive's central
directory itself (a couple of megabytes) to learn where those entries live, so
only the names are baked in - and every fetch is verified against the line's own
`Linky.txt` in case the names are ever reassigned.

The archive is republished a few times a week and reassigns the names when it is,
which makes a shipped mapping stale rather than wrong: the check in the app then
finds no entry for the line and reports it as missing. Run this again whenever
that happens - `make mapping` downloads the archive and does it:

    make mapping
    python3 tools/jdf_lines_mapping.py /tmp/jdf/JDF.zip VdvLive/Resources/jdf-lines.json
"""

import io
import json
import os
import sys
import zipfile

# Districts of the Vysočina Region. A line is kept when any of its stops is in
# one of them, which also keeps the lines that cross the border.
VYSOCINA = {"JI", "TR", "PE", "HB", "ZR"}


def field(row, index):
    parts = row.strip().split('","')
    parts[0] = parts[0].lstrip('"')
    parts[-1] = parts[-1].rstrip('";')
    return parts[index] if index < len(parts) else ""


def version_of(inner):
    """The version stamp the archive carries in every entry.

    Written into the mapping so a stale one can be told from a current one by
    looking at the file: the date is the day the data was published.
    """
    if "VerzeJDF.txt" not in inner.namelist():
        return {}
    row = inner.read("VerzeJDF.txt").decode("cp1250").splitlines()[0]
    return {"format": field(row, 0), "date": field(row, 4)}


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    archive_path, output_path = sys.argv[1], sys.argv[2]

    mapping = {}
    entries = 0
    stamp = {}
    with zipfile.ZipFile(archive_path) as outer:
        for name in outer.namelist():
            entries += 1
            with zipfile.ZipFile(io.BytesIO(outer.read(name))) as inner:
                if not stamp:
                    stamp = version_of(inner)
                linky = field(inner.read("Linky.txt").decode("cp1250").splitlines()[0], 0)
                districts = {
                    field(row, 4)
                    for row in inner.read("Zastavky.txt").decode("cp1250").splitlines()
                }
            if not districts & VYSOCINA:
                continue
            mapping.setdefault(linky, []).append(name)

    document = {
        "source": "https://portal.cisjr.cz/pub/JDF/JDF.zip",
        "note": "Line number to archive entry. Generated by tools/jdf_lines_mapping.py.",
        "archive": {"bytes": os.path.getsize(archive_path), **stamp},
        "lines": {line: sorted(names) for line, names in sorted(mapping.items())},
    }
    with open(output_path, "w", encoding="utf-8") as handle:
        json.dump(document, handle, ensure_ascii=False, indent=1, sort_keys=True)
        handle.write("\n")

    print(
        f"scanned {entries} entries of the {stamp.get('date', 'undated')} archive, "
        f"kept {len(mapping)} lines -> {output_path}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
